language: julia

julia:
  - 1.5

python: 
  - 3.6 

os:
  - linux

notifications:
  email: false
before_install:
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --color=yes --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: skip
